const mockedUser = [
    {
        firstName: "jean",
        lastName: "bon",
        department: "Sales",
        street: "piemontaise caille",
        city: "houston",
        usState: "AU",
        birthDate: "06/03/1980",
        startDate: "12/04/2021",
        zipCode: "03567",
    },
    {
        firstName: "emma",
        lastName: "rhinades",
        department: "Legal",
        street: "judgment street",
        city: "Dallas",
        usState: "TX",
        birthDate: "30/11/1998",
        startDate: "10/08/2020",
        zipCode: "05567",
    },
    {
        firstName: "Marcel",
        lastName: "Serres-Dents",
        department: "Human Ressources",
        street: "dancing dogs",
        city: "Calais",
        usState: "AZ",
        birthDate: "04/04/1984",
        startDate: "15/05/2011",
        zipCode: "0334452",
    },
    {
        firstName: "Jeanne",
        lastName: "Auscoure",
        department: "Marketing",
        street: "saint pancras",
        city: "London",
        usState: "ST",
        birthDate: "06/01/1412",
        startDate: "12/04/2022",
        zipCode: "354347",
    },
    {
        firstName: "jean",
        lastName: "bon",
        department: "Sales",
        street: "piemontaise caille",
        city: "houston",
        usState: "AU",
        birthDate: "06/03/1980",
        startDate: "12/04/2021",
        zipCode: "03567",
    },
    {
        firstName: "emma",
        lastName: "rhinades",
        department: "Legal",
        street: "judgment street",
        city: "Dallas",
        usState: "TX",
        birthDate: "30/11/1998",
        startDate: "10/08/2020",
        zipCode: "05567",
    },
    {
        firstName: "Marcel",
        lastName: "Serres-Dents",
        department: "Human Ressources",
        street: "dancing dogs",
        city: "Calais",
        usState: "AZ",
        birthDate: "04/04/1984",
        startDate: "15/05/2011",
        zipCode: "0334452",
    },
    {
        firstName: "Jeanne",
        lastName: "Auscoure",
        department: "Marketing",
        street: "saint pancras",
        city: "London",
        usState: "ST",
        birthDate: "06/01/1412",
        startDate: "12/04/2022",
        zipCode: "354347",
    },
    {
        firstName: "jean",
        lastName: "bon",
        department: "Sales",
        street: "piemontaise caille",
        city: "houston",
        usState: "AU",
        birthDate: "06/03/1980",
        startDate: "12/04/2021",
        zipCode: "03567",
    },
    {
        firstName: "emma",
        lastName: "rhinades",
        department: "Legal",
        street: "judgment street",
        city: "Dallas",
        usState: "TX",
        birthDate: "30/11/1998",
        startDate: "10/08/2020",
        zipCode: "05567",
    },
    {
        firstName: "Marcel",
        lastName: "Serres-Dents",
        department: "Human Ressources",
        street: "dancing dogs",
        city: "Calais",
        usState: "AZ",
        birthDate: "04/04/1984",
        startDate: "15/05/2011",
        zipCode: "0334452",
    },
    {
        firstName: "Jeanne",
        lastName: "Auscoure",
        department: "Marketing",
        street: "saint pancras",
        city: "London",
        usState: "ST",
        birthDate: "06/01/1412",
        startDate: "12/04/2022",
        zipCode: "354347",
    },

]
export default mockedUser;